# Generated by Django 3.2.8 on 2021-10-30 15:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='article_image'),
        ),
    ]
