# Generated by Django 3.2.8 on 2021-10-28 14:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image'),
        ),
    ]
